Import Numpy and Pandas

In [1]:
import numpy as np
import pandas as pd

Load a pandas dataframe

In [2]:
df = pd.read_csv('https://sololearn.com/uploads/files/titanic.csv')
df.head()

Survived  Pclass     Sex   Age  Siblings/Spouses  Parents/Children     Fare
0         0       3    male  22.0                 1                 0   7.2500
1         1       1  female  38.0                 1                 0  71.2833
2         1       3  female  26.0                 0                 0   7.9250
3         1       1  female  35.0                 1                 0  53.1000
4         0       3    male  35.0                 0                 0   8.0500

Convert a pandas series to a numpy array

In [3]:
df['Fare'].values

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
        41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,  21.6792,
        17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,  61.9792,
        35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,   7.2292,
        80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,  10.5   ,
         8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,  73.5   ,
        14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,  29.    ,
        12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,  10.5   ,
        15.85  ,  34.375 ,   8.05  , 263.    ,   8.05  ,   8.0

Convert a pandas dataframe to a numpy array (2 dimensional)

In [4]:
print(df[['Pclass', 'Fare', 'Age']].values)

[[ 3.      7.25   22.    ]
 [ 1.     71.2833 38.    ]
 [ 3.      7.925  26.    ]
 ...
 [ 3.     23.45    7.    ]
 [ 1.     30.     26.    ]
 [ 3.      7.75   32.    ]]


To determine the size of our numpy array we use the shape attribute.

In [5]:
arr = df[['Pclass', 'Fare', 'Age']].values
arr.shape

(887, 3)

Selecting a single element form the array

In [6]:
arr[0, 1]

7.25

Selecting a single row

In [7]:
arr[0]

array([ 3.  ,  7.25, 22.  ])

Select a single column

In [8]:
arr[:, 2]

array([22.  , 38.  , 26.  , 35.  , 35.  , 27.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 23.  ,
       31.  , 22.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 26.  ,
       19.  , 24.  , 23.  , 40.  , 48.  , 18.  , 66.  , 28.  , 42.  ,
       18.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 30.  ,
       20.  , 27.  , 16.  , 18.  ,  7.  , 21.  , 49.  , 29.  , 65.  ,
       46.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,  4.  ,
       64.  ,  7.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  , 21.  ,
       26.  , 32.  , 25.  , 23.  , 28.  ,  0.83, 30.  , 22.  , 29.  ,
       31.  , 28.  , 17.  , 33.  , 16.  , 20.  , 23.  , 24.  , 29.  ,
       20.  , 46.  , 26.  , 59.  , 22.  , 71.  , 23.  , 34.  , 34.  ,
       28.  , 29.  , 21.  , 33.  , 37.  , 28.  , 21.  , 29.  , 38.  ,
       28.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 , 29.  ,
       24.  ,  2.  , 21.  , 19.  , 32.5 , 32.5 , 54.  , 12.  , 19.  ,
       24.  ,  2.  ,

Masking: selecting all the rows that fulfull a certain criteria.  
First we create a mask of boolean values and then we use the mask to select the values that fulfull the criteria defined by the mask.

In [9]:
mask = arr[:, 2] < 18    # Age less than 18 years
arr[mask]

array([[  3.    ,  21.075 ,   2.    ],
       [  2.    ,  30.0708,  14.    ],
       [  3.    ,  16.7   ,   4.    ],
       [  3.    ,   7.8542,  14.    ],
       [  3.    ,  29.125 ,   2.    ],
       [  3.    ,   8.0292,  15.    ],
       [  3.    ,  21.075 ,   8.    ],
       [  3.    ,  11.2417,  14.    ],
       [  2.    ,  41.5792,   3.    ],
       [  3.    ,  21.6792,  16.    ],
       [  3.    ,  39.6875,   7.    ],
       [  2.    ,  27.75  ,   5.    ],
       [  3.    ,  46.9   ,  11.    ],
       [  3.    ,  27.9   ,   4.    ],
       [  3.    ,  15.2458,   7.    ],
       [  3.    ,   7.925 ,  17.    ],
       [  3.    ,  46.9   ,  16.    ],
       [  2.    ,  29.    ,   0.83  ],
       [  2.    ,  10.5   ,  17.    ],
       [  3.    ,  34.375 ,  16.    ],
       [  3.    ,  14.4542,  14.5   ],
       [  3.    ,  14.4583,  17.    ],
       [  3.    ,  31.275 ,   2.    ],
       [  3.    ,  11.2417,  12.    ],
       [  3.    ,  22.3583,   2.    ],
       [  3.    ,   9.216

We don't need to explicitly define a mask, we can also do this in a single line.

In [10]:
arr[arr[:, 2] < 18]

array([[  3.    ,  21.075 ,   2.    ],
       [  2.    ,  30.0708,  14.    ],
       [  3.    ,  16.7   ,   4.    ],
       [  3.    ,   7.8542,  14.    ],
       [  3.    ,  29.125 ,   2.    ],
       [  3.    ,   8.0292,  15.    ],
       [  3.    ,  21.075 ,   8.    ],
       [  3.    ,  11.2417,  14.    ],
       [  2.    ,  41.5792,   3.    ],
       [  3.    ,  21.6792,  16.    ],
       [  3.    ,  39.6875,   7.    ],
       [  2.    ,  27.75  ,   5.    ],
       [  3.    ,  46.9   ,  11.    ],
       [  3.    ,  27.9   ,   4.    ],
       [  3.    ,  15.2458,   7.    ],
       [  3.    ,   7.925 ,  17.    ],
       [  3.    ,  46.9   ,  16.    ],
       [  2.    ,  29.    ,   0.83  ],
       [  2.    ,  10.5   ,  17.    ],
       [  3.    ,  34.375 ,  16.    ],
       [  3.    ,  14.4542,  14.5   ],
       [  3.    ,  14.4583,  17.    ],
       [  3.    ,  31.275 ,   2.    ],
       [  3.    ,  11.2417,  12.    ],
       [  3.    ,  22.3583,   2.    ],
       [  3.    ,   9.216

Another way to use the mask is to get number of children on the titanic

In [12]:
(arr[:, 2] > 18).sum()  # returns the number of true values. 

721